apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'YOUR_GIT_REPO_URL' 
    targetRevision: master         
    path: helm-chart/test-app
  destination:
    server: [https://kubernetes.default.svc](https://kubernetes.default.svc)
    namespace: nb-challenge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true